---
- name: Install generated UPF configuration
  ansible.builtin.template:
    src: 'open5gs/upf.yaml.j2'
    dest: '{{ epc_open5gs_config_dir }}/upf.yaml'
    owner: root
    group: root
    mode: '0644'
  tags:
    - config
- name: Create Open5GS UPF container
  community.docker.docker_container:
    name: lc-upf
    image: myriadrf/open5gs:{{ epc_open5gs_version }}
    pull: yes
    state: started
    restart: yes
    restart_policy: always
    privileged: true
    capabilities: 
      - NET_ADMIN
    sysctls:
      net.ipv4.ip_forward: 1
    env:
      COMPONENT_NAME: upf-1
    networks:
      - name: lc
        ipv4_address: '{{ epc_upf_bind_addr }}'
    volumes:
      - /etc/lc/open5gs:/etc/lc/open5gs:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - '2152/udp'
      - '8805/udp'
      - '9091/tcp'
  tags:
    - container
