---
- ansible.builtin.include_role:
    name: geerlingguy.docker
  tags:
    - docker
- name: Install pip packages 
  ansible.builtin.pip:
    name: '{{ item.name }}'
    state: present
  loop: '{{ pip_install_packages }}'
  vars:
    pip_install_packages:
      - name: docker
      - name: mysqlclient
  tags:
    - pip
- name: Create base configuration directory
  ansible.builtin.file:
    path: '{{ lc_config_dir }}'
    state: directory
    mode: '0755'
  tags:
    - config 
- name: Create LibreCellular private network
  community.docker.docker_network:
    name: '{{ lc_docker_network_name }}'
    ipam_config:
      - subnet: '{{ lc_docker_network_subnet}}'
        gateway: '{{ lc_docker_network_gateway }}'
  tags:
    - docker
    - network
